---
# tasks file for opdk-setup-validate-cleanup

- name: Validate OPDK Installation
  ignore_errors: yes
  shell: '{{ apigee_service }} apigee-validate clean -f {{ apigee_validate_config_file }}'
  when: opdk_version | version_compare('4.16.01', '==')

- name: Validate OPDK Installation
  expect:
    command: '{{ apigee_service }} apigee-validate clean -f {{ apigee_validate_config_file }}'
    responses:
      'Do you really want to continue? y/n': 'y'
  when: opdk_version | version_compare('4.16.01', '>')
